#!/bin/bash
#
# aurget 2.0 config file, generated Thu, 27 May 2010 16:16:27 -0500
#
# use any valid bash to populate the variables.
#
# any config value can be set at runtime via --option=value
#
###

#
# the exact command used to install the built packages. --asdeps will be
# automatically added when appropriate. use --popt to add any
# additional options at runtime.
###
pacman_command='sudo pacman -U'

#
# the exact command used to build packages. use --mopt to add any
# additional options at runtime.
###
makepkg_command='makepkg -s --noconfirm'

#
# by default, the value of $EDITOR is used to edit pkgbuilds.
# you can override this here if you'd like.
###
pkgbuild_editor=

#
# where to save built packages. leave empty to use the value of PKGDEST
# in makepkg.conf (or the current working directory if that's blank).
###
package_directory='/home/lrm/builds'

#
# where to download source files and do the actual building. aurget
# will create subdirectories named after the packages being built.
# leave blank to the use current working directory. this replaces the
# deprecated option source_directory.
###
build_directory='/home/lrm/builds'

#
# set this as false to not remove all source files after building a
# package. this has no effect on sources saved using the SRCDEST
# setting in makepkg.conf.
###
discard_sources=true

#
# set this to override the above when building development packages
# as defined by development_regex.
###
dont_discard_devels=true

#
# this regex is matched against package names to determine if a package
# is a development package. development packages are not checked for
# available upgrades but can be upgraded explicitly by passing --devel.
###
development_regex='.*-git$\|.*-hg$\|.*-svn$\|.*-darcs$\|.*-cvs$'

#
# the default sync mode is the behavior when aurget -S <package> is
# called. it can be one of install, build, or download.
###
sync_mode=install

#
# set this as false to stop aurget from prompting you to edit all
# pkgbuilds before sourcing.
###
prompt_to_edit=true

#
# set this as true to automatically resolve all aur dependencies.
###
resolve_dependencies=false

#
# this is a space separated list of package names to be ignored.
###
ignore_packages=

#
# by default, aurget uses no color. uncomment to enable/customize.
###
nocolor="\e[0m"   # reset color
colorW="\e[1;37m" # white
colorB="\e[1;34m" # blue
colorR="\e[1;31m" # red
colorG="\e[1;32m" # green
colorY="\e[1;33m" # yellow
colorM="\e[1;35m" # magenta


# don't edit this:
version="2.8-1"
