"----------------------------------------------  vim:ts=4:sw=4:sts=4:et:ft=vim
" vimrc - configure VIM editor
" ---------------------------------------------------------------------------- 

set nocompatible
filetype off

let mapleader = ","
let maplocalleader = "\\"

" Auto-initialize vundle if we don't already have it:
" http://www.erikzaadi.com/2012/03/19/auto-installing-vundle-from-your-vimrc/
let need_vundle_init=1
let vundle_readme=expand('~/.vim/bundle/vundle/README.md')
if !filereadable(vundle_readme)
    echo "Installing Vundle..\n"
    silent !mkdir -p ~/.vim/bundle
    silent !git clone https://github.com/gmarik/vundle ~/.vim/bundle/vundle
    let need_vundle_init=0
endif

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" vundle manages vundle, required
Bundle 'gmarik/vundle'

Bundle 'Lokaltog/vim-powerline'
Bundle 'acustodioo/vim-tmux'
Bundle 'chrismetcalf/vim-yankring'
Bundle 'godlygeek/tabular'
Bundle 'kien/ctrlp.vim'
Bundle 'mileszs/ack.vim'
Bundle 'mirell/vim-matchit'
Bundle 'scrooloose/nerdcommenter'
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/syntastic'
Bundle 'sjl/threesome.vim'
Bundle 'tpope/vim-fugitive'
Bundle 'tpope/vim-repeat'
Bundle 'tpope/vim-surround'
Bundle 'tpope/vim-unimpaired'
Bundle 'tsaleh/vim-align'

Bundle 'Twinside/vim-syntax-haskell-cabal'
Bundle 'lukerandall/haskellmode-vim'

" colors
Bundle 'sjl/badwolf'
Bundle 'altercation/vim-colors-solarized'
Bundle 'tomasr/molokai'

if need_vundle_init == 0
    echo "Installing Bundles, please ignore key map error messages\n"
    :BundleInstall
endif

filetype plugin indent on
syntax on 
set background=dark
let g:solarized_termcolors=256
colorscheme solarized

set encoding=utf8
set modelines=1
set laststatus=2
set completeopt=longest,menuone,preview
set number
set ruler
set autoread 
set backspace=indent,eol,start
set binary
set cinoptions=:0,(s,u0,U1,g0,t0
set hidden 
set history=1000
set incsearch
set laststatus=2
set showbreak=?
set notimeout
set ttimeout
set ttimeoutlen=10
set noeol
set number 
set ruler 
set showcmd 
set matchtime=2
set completeopt=longest,menuone,preview
set autoindent
set tabstop=4 
set textwidth=80
set shiftwidth=4 
set softtabstop=4
set expandtab
set wrap 
set formatoptions=qrn1
set visualbell 
set wildignore=.svn,CVS,.git,.hg,*.o,*.a,*.class,*.mo,*.la,*.so,*.obj,*.swp,*.jpg,*.png,*.?xpm,*.gif,.DS_Store,*.aux,*.out,*.toc
set wildmenu 
set dictionary=/usr/share/dict/words
set ignorecase
set smartcase
set showmatch
set gdefault
set hlsearch

let g:Powerline_symbols = 'unicode'
let g:Powerline_cache_enabled = 1

let g:syntastic_enable_signs = 1
let g:syntastic_auto_loc_list = 1

" Highlight merge conflict markers
match ErrorMsg '^\(<\|=\|>\)\{7\}\([^=].\+\)\?$'

map Y y$
map <Tab> %
noremap <Silent><Leader>/ :nohls<CR>
inoremap jk <Esc>

noremap <Leader><Space> :noh<CR>:call clearmatches()<CR>
nmap <C-u> :NERDTreeToggle<CR>
